### ISSUE TITLE
tabular input fails

### ISSUE THREAD

**Issue by bernt-matthias** [nickeener/sarscov2formatter#2]
I guess pandas is guessing the data types for the columns (e.g. date column as int64). Which leads to problems in dompung the json: 

```
Traceback (most recent call last):
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/bin/sarscov2formatter", line 10, in <module>
    sys.exit(main())
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/site-packages/sarscov2formatter/cli.py", line 12, in main
    formatter(args.alignment, args.metadata)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/site-packages/sarscov2formatter/__init__.py", line 193, in formatter
    json.dump(meta, file, indent=1, sort_keys=True)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```
I guess you want to load all columns as string, except for `"None"` as `None`.

Background: For the Galaxy test the output is instable when "ncbi" is used as source. Probably because the data changes. So I tried to implement a test for the tabular data input.

**Comment by bernt-matthias** [comment]
Also I was wondering why the tool needs 1.7GB of memory for the (small Galaxy test case) .. for the ncbi input.

**Comment by bgruening** [comment]
@bernt-matthias I assume this file grows in size: https://www.ncbi.nlm.nih.gov/projects/genome/sars-cov-2-seqs/ncov-sequences.yaml and it loaded completely in memory at once :(

**Comment by bernt-matthias** [comment]
Traceback is 

```
Traceback (most recent call last):
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/bin/sarscov2formatter", line 10, in <module>
    sys.exit(main())
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/site-packages/sarscov2formatter/cli.py", line 13, in main
    formatter(args.alignment, args.metadata, args.ncbimetadata)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/site-packages/sarscov2formatter/__init__.py", line 209, in formatter
    json.dump(meta, file, indent=1, sort_keys=True)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/berntm/miniconda3/envs/__sarscov2formatter@0.5.4/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```

which is because pandas read_csv autodetects the 2nd col as integer.
